### ISSUE TITLE
Allow configurable description length

### ISSUE THREAD

**Issue by SeanLF** [Shopify/cli-kit#212]
Instead of raising an exception if a description is over 80 characters long, what do you think of either:
- allowing the maximum length to be configured by the user (defaulted to 80)
- cropping the description to the first 80 characters with an ellipsis at the end

https://github.com/Shopify/cli-kit/blob/a7da9034ca0207a5594cd6412f9de361928f48ee/lib/cli/kit/command_help.rb#L191-L192

**Comment by lugray** [comment]
This should definitely be configurable by the app. I'd be happy to review a PR that made this change.

**Comment by lugray** [comment]
Closed in #226
