### ISSUE TITLE
system output without format

### ISSUE THREAD

**Issue by pepibumur** [Shopify/cli-kit#32]
### Context
We are using the `CLI::Kit::System` helper to run commands from our project. One of those commands that we execute outputs the logs using colors and some other formatting. 

### What
We expect the output from system to keep the format, however, it outputs the logs with no formatting. 

Might it be related to the encoding that the `system` method uses internally?

**Comment by lugray** [comment]
I can't replicate.
![screen shot 2018-06-25 at 9 14 51 am](https://user-images.githubusercontent.com/6557101/41852173-636b4388-7858-11e8-86cc-8a1d189143c5.png)

Commands which print with colour often automatically disable that when running in a non-interactive context.  If you execute `your-command | cat`, does it still have colour?

**Comment by pepibumur** [comment]
You are right @lugray. It has nothing to do with the `system` method itself. I was calling the command with the wrong arguments and it was not formatting anything. Thank you very much!

**Comment by pepibumur** [comment]
Actually,

**Comment by lugray** [comment]
What happens if you add ` | cat` after `xcpretty -s` at the prompt?

**Comment by lugray** [comment]
Offline: `| cat` did remove colour.  xcpretty detects interactivity by default, but provides `--[no-]color`, which can be used to force either way.
