### ISSUE TITLE
Questions about `option` and `option!`

### ISSUE THREAD

**Issue by bmassemin** [Shopify/cli-kit#340]
I'm trying to code a new command line using `cli-kit`, and I was wondering if I'm correctly understanding`option` and `option!`.
My understanding is `option` is an optional parameter, while `option!` is a required parameter.
But looking at the code they are both not `required` ([here](https://github.com/Shopify/cli-kit/blob/main/lib/cli/kit/opts.rb#L68) and [here](https://github.com/Shopify/cli-kit/blob/main/lib/cli/kit/opts.rb#L89)).

Also, if I try to set a non Nil `default` with `option`, I have the following error message:
```
ArgumentError: declare options with non-nil defaults using `option!` instead of `option`
```
I guess it should be `option` instead of `option!`.

Let me know if I misunderstood how it works, and also how I can use something same as `option` with `required`

**Comment by lugray** [comment]
`option!` will always return a string, giving the default value if one is not specified at the command line.  `option` will sometimes give a string, and sometimes a `nil`. You can see this in the Sorbet signatures:
https://github.com/Shopify/cli-kit/blob/aff27136c740bb94f9c72b2e791cb23ad7e6be68/lib/cli/kit/opts.rb#L59-L61
vs

https://github.com/Shopify/cli-kit/blob/aff27136c740bb94f9c72b2e791cb23ad7e6be68/lib/cli/kit/opts.rb#L84-L86
